### ISSUE TITLE
Angular directory resolves incorrectly

### ISSUE THREAD

**Issue by SuperJugy** [single-spa/create-single-spa#206]
Hi,

I was using this tool fine last week. but today I am getting this error:
```
C:\repos\microfrontendPoC\app1 >npx create-single-spa --moduleType app-parcel
(node:21216) ExperimentalWarning: The fs.promises API is experimental
? Directory for new project .
? Which framework do you want to use? angular
? Project name (can use letters, numbers, dash or underscore) app1
events.js:174
      throw er; // Unhandled 'error' event
      ^

ReferenceError: path is not defined
    at SingleSpaAngularGenerator.runAngularCli (C:\Users\dev\AppData\Roaming\npm-cache\_npx\21216\node_modules\create-single-spa\node_modules\generator-single-spa\src\angular\generator-single-spa-angular.js:46:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\dev\AppData\Roaming\npm-cache\_npx\21216\node_modules\create-single-spa\node_modules\yeoman-generator\lib\index.js:1022:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Any idea what could be happening here?

**Comment by filoxo** [comment]
Hi @SuperJugy thanks for reporting this issue! I found what the problem was, and have fixed it in [create-single-spa@1.17.1](https://github.com/single-spa/create-single-spa/releases/tag/v1.17.1).

**Comment by SuperJugy** [comment]
Hi,

Now I am facing a new issue:

```
C:\repos\microfrontendPoC\app1>create-single-spa --moduleType app-parcel
(node:22484) ExperimentalWarning: The fs.promises API is experimental
? Directory for new project .
? Which framework do you want to use? angular
? Project name (can use letters, numbers, dash or underscore) app1
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss
               ]
ENOENT: no such file or directory, mkdir 'C:\repos\microfrontendPoC\app1\C:'
```

it seems to be trying to append the absolute path to the relative path or something?

**Comment by filoxo** [comment]
Ok, yea. Let's reopen this issue then, even though this is a different error. Can you also share what version of the angular-cli you're using?

**Comment by SuperJugy** [comment]
I tried without the angluar-cli installed, then installed it globally (latest version) neither approach work.

**Comment by denniscalazans** [comment]
Whem I am at 
/Users/myuser/projects/my-new-angular-app 
and I use create-single-spa using "." as the place

The cli creates the app in this folder

/Users/myuser/projects/Users/myuser/projects/my-new-angular-app 

Please take a look.

**Comment by SuperJugy** [comment]
Yeah, like I said, it is trying to add the absolute path to the relative path and in windows it creates an invalid path since you cannot have `:` in the path after the drive

**Comment by filoxo** [comment]
Excellent, thank you both for your input. The path resolves correctly on Mac, so this seems to be a Windows-only problem. I'll try to test this again on a Windows computer.

**Comment by SuperJugy** [comment]
I tried with version 1.15 and 1.14 and it gives the same error, which is weird because the tool was working for me last week. Could it be the angular-cli version that changed? do you have a globally installed angular-cli which could be resolving the path differently?

**Comment by filoxo** [comment]
That definitely could be. The angular-cli is a moving target for us because they have very poor documentation and release breaking changes without much information. I personally try to use the latest for my testing, mostly because its impractical to test against every single version of every cli. 

There does appear to be some changes to the behavior [here](https://github.com/angular/angular-cli/releases/tag/v10.1.3) but I can't tell if that would affect this. 

I may have misunderstood the [`new --directory` flag](https://angular.io/cli/new#options). I assumed it could work with an absolute path so the [path is resolved before being passed to the angular-cli command](https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/angular/generator-single-spa-angular.js#L54-L55) but with paths I see from both your reports that may not be true.

**Comment by SuperJugy** [comment]
Yeah ,it does seem to be expecting a name, not a path, or at least not an absolute one. The problem is if someone using your tool decides to give you an absolute path, it might fail as well

**Comment by SuperJugy** [comment]
OMG, I tried installing the version 1.14.1 to workaround this issue in the meantime, but it seems to be downloading the latest version of the generator library which has this issue... So now I am stuck :'(

**Comment by filoxo** [comment]
As a workaround, you might try `npx create-single-spa@1.14.1`. Sorry for the inconvenience. I'll try to fix this as soon as I can, but I also have a full-time job so it might not be until later or even tomorrow.

**Comment by SuperJugy** [comment]
I just went to the node_modules and altered the generator file :P able to get back to work now.

BTW your solution wouldn't work. Apparently the 1.14.1 version will still get the latest version of the generator library which is 1.17 and has the issue. You might want to lock the versions together

**Comment by filoxo** [comment]
Oh, yea, good call. I'll fix [that](https://github.com/single-spa/create-single-spa/blob/v1.14.1/packages/create-single-spa/package.json#L11) as well when I can.

**Comment by filoxo** [comment]
@SuperJugy @denniscalazans I've released [create-single-spa@1.17.2](https://github.com/single-spa/create-single-spa/releases/tag/v1.17.2) with the fix for this. Please let me know if there are any remaining issues.
